{
    "button":[
    {
        "type":"view",
        "name":"购买特产",
        "url":"http://pys.b-wmobile.com/users/wx_menu_point?referer_key=CLICK_URL_TECHAN&from=sub"
    },
    {
        "name":"个人中心",
        "sub_button":[
            {
                "type":"view",
                "name":"我的订单",
                "url":"http://pys.b-wmobile.com/users/wx_menu_point?referer_key=CLICK_URL_MINE&do_wx_auth_if_not_log_in=1&from=sub"
            },
            {
                "type":"view",
                "name":"我要分享",
                "url":"http://wsq.qq.com/reflow/177650290"
            },
            {
                "type":"view",
                "name":"售后服务",
                "url":"http://pys.b-wmobile.com/users/wx_menu_point?referer_key=CLICK_URL_SALE_AFTER_SAIL&from=sub"
            },
            {
                "type":"click",
                "name":"关注服务号",
                "key":"CLICK_GUANZHU_FUWUHAO"
            },
            {
                "type":"click",
                "name":"绑定旧版数据",
                "key":"CLICK_URL_BINDING"
            }
        ]
    },
    {
        "name":"分享社区",
        "sub_button":[
            {
                "type":"view",
                "name":"分享社区",
                "url":"http://wsq.qq.com/reflow/177650290"
            },
            {
                "type":"view",
                "name":"试吃团",
                "url":"http://pys.b-wmobile.com/users/wx_menu_point?referer_key=CLICK_URL_SHICHITUAN&from=sub"
            },
            {
                "type":"view",
                "name":"加入试吃",
                "url":"http://www.mikecrm.com/f.php?t=3DGEyQ"
            }]
    }
    ]
}