{
    "button":[
    {
        "type":"view",
        "name":"购买特产",
        "url":"http://www.pyshuo.com/users/wx_menu_point?referer_key=CLICK_URL_TECHAN&from=service&_sl=wx.sv.home"
    },
    {
        "type":"view",
        "name":"美食团",
        "url":"http://www.tongshijia.com/tuan_teams/mei_shi_tuan.html?_sl=wx.sv.mst"
    },
    {
        "name":"个人中心",
        "sub_button":[
            {
                "type":"view",
                "name":"个人中心",
                "url":"http://www.pyshuo.com/users/me.html?from=service&_sl=wx.sv.uc"
            },
            {
                "type":"view",
                "name":"我的订单",
                "url":"http://www.pyshuo.com/users/wx_menu_point?referer_key=CLICK_URL_MINE&do_wx_auth_if_not_log_in=1&from=service&_sl=wx.sv.orders"
            },
            {
                "type":"view",
                "name":"我的优惠券",
                "url":"http://www.pyshuo.com/users/wx_menu_point?referer_key=CLICK_URL_COUPON&do_wx_auth_if_not_log_in=1&from=service&_sl=wx.sv.coupon"
            },
            {
                "type":"view",
                "name":"推荐有礼",
                "url":"http://www.pyshuo.com/users/wx_menu_point?referer_key=CLICK_URL_REFER&do_wx_auth_if_not_log_in=1&from=service&_sl=wx.sv.refer"
            },
            {
                "type":"view",
                "name":"售后服务",
                "url":"http://www.pyshuo.com/users/wx_menu_point?referer_key=CLICK_URL_SALE_AFTER_SAIL&from=service&_sl=wx.sv.sv"
            }
        ]
    }
]
}