{
    "button":[
    {
        "type":"view",
        "name":"购买特产",
        "url":"http://sh.tongshijia.com/weshares/index?from=weixin"
    },
    {
        "name":"我要分享",
        "sub_button":[
          {
            "type":"view",
            "name":"我要分享",
            "url":"http://sh.tongshijia.com/weshares/add.html?from=weixin"
          },
          {
            "type":"view",
            "name":"我的分享",
            "url":"http://sh.tongshijia.com/weshares/my_shares_list.html?from=weixin"
          },
          {
            "type":"view",
            "name":"团长加入指南",
            "url":"https://mp.weixin.qq.com/s?__biz=MzIwNzMyNjk5NQ==&mid=100000004&idx=1&sn=9c517b41f173a37bcd0b62efa940bc4b"
          },
          {
            "type":"view",
            "name":"商家入驻指南",
            "url":"https://mp.weixin.qq.com/s?__biz=MzIwNzMyNjk5NQ==&mid=100000017&idx=1&sn=87f2be4af5a5399cf1cbe68c0734b141"
          }
        ]
    },
    {
        "name":"个人中心",
        "sub_button":[
            {
                "type":"view",
                "name":"个人中心",
                "url":"http://sh.tongshijia.com/users/wx_menu_point?referer_key=MY_SHARE_INFO&from=service&_sl=wx.sv.home"
            },
            {
                "type":"click",
                "name":"售后服务",
                "key":"V1001_C_S"
            }
        ]
    }
]
}