{
    "button":[
    {
        "type":"view",
        "name":"购买特产",
        "url":"http://pys.b-wmobile.com/users/wx_menu_point?referer_key=CLICK_URL_TECHAN&from=service"
    },
    {
        "type":"view",
        "name":"苹果游戏",
        "url":"http://pys.b-wmobile.com/apple_201410/index.html"
    },
    {
        "name":"个人中心",
        "sub_button":[
            {
                "type":"view",
                "name":"我的订单",
                "url":"http://pys.b-wmobile.com/users/wx_menu_point?referer_key=CLICK_URL_MINE&do_wx_auth_if_not_log_in=1&from=service"
            },
            {
                "type":"view",
                "name":"我要分享",
                "url":"http://wsq.qq.com/reflow/177650290"
            },
            {
                "type":"view",
                "name":"加入试吃",
                "url":"http://www.mikecrm.com/f.php?t=3DGEyQ"
            },
            {
                "type":"view",
                "name":"售后服务",
                "url":"http://pys.b-wmobile.com/users/wx_menu_point?referer_key=CLICK_URL_SALE_AFTER_SAIL&from=service"
            },
            {
                "type":"click",
                "name":"关注服务号",
                "key":"CLICK_GUANZHU_FUWUHAO"
            }
        ]
    }
]
}