{
    "button":[
    {
        "type":"view",
        "name":"购买特产",
        "url":"http://www.pengyoushuo.com.cn/techan.html"
    },
    {
        "name":"个人中心",
        "sub_button":[
            {
                "type":"view",
                "name":"我的订单",
                "url":"http://www.pengyoushuo.com.cn/orders/mine.html"
            },
            {
                "type":"view",
                "name":"我要分享",
                "url":"http://www.mikecrm.com/f.php?t=hyhfVO"
            },
            {
                "type":"view",
                "name":"售后服务",
                "url":"http://www.pengyoushuo.com.cn/articles/view/377"
            }]
    },
    {
        "name":"试吃团",
        "sub_button":[
            {
                "type":"view",
                "name":"试吃评价",
                "url":"http://www.pengyoushuo.com.cn/shichituan.html"
            },
            {
                "type":"view",
                "name":"加入试吃",
                "url":"http://www.mikecrm.com/f.php?t=3DGEyQ"
            }]
    },

    ]
}