{
    "button":[
    {
        "type":"view",
        "name":"购买特产",
        "url":"http://www.pyshuo.com/users/wx_menu_point?referer_key=CLICK_URL_TECHAN&from=service&_sl=wx.sv.home"
    },
    {
        "name":"我要分享",
        "sub_button":[
          {
            "type":"view",
            "name":"我要分享",
            "url":"http://www.tongshijia.com/weshares/add"
          },
          {
            "type":"view",
            "name":"我的分享",
            "url":"http://www.tongshijia.com/weshares/user_share_info/"
          }
        ]
    },
    {
        "name":"个人中心",
        "sub_button":[
            {
                "type":"view",
                "name":"个人中心",
                "url":"http://www.pyshuo.com/weshares/user_share_info?from=service&_sl=wx.sv.uc"
            },
            {
                "type":"view",
                "name":"售后服务",
                "url":"http://www.pyshuo.com/users/wx_menu_point?referer_key=CLICK_URL_SALE_AFTER_SAIL&from=service&_sl=wx.sv.sv"
            }
        ]
    }
]
}